# -*- coding: utf-8 -*-
"""WaterJug_Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJmNv2LCqxgaDHmy1B7MI4WobnIVySLp

# Water Jug Problem using Search Algorithms

### Objective:
Implement BFS, DFS, and A* search algorithms to solve the classic **Water Jug Problem**.

- Jug1 capacity = 4 liters  
- Jug2 capacity = 3 liters  
- Goal = Measure exactly 2 liters
"""

from collections import deque

JUG1 = 4
JUG2 = 3
GOAL = 1

def water_jug_bfs():
    start = (0, 0)
    visited = set()
    queue = deque([[start]])

    while queue:
        path = queue.popleft()
        state = path[-1]

        if state[0] == GOAL or state[1] == GOAL:
            return path

        if state in visited:
            continue
        visited.add(state)

        x, y = state

        next_states = [
            (JUG1, y),
            (x, JUG2),
            (0, y),
            (x, 0),
            (x - min(x, JUG2 - y), y + min(x, JUG2 - y)),
            (x + min(y, JUG1 - x), y - min(y, JUG1 - x))
        ]

        for nxt in next_states:
            if nxt not in visited:
                new_path = list(path)
                new_path.append(nxt)
                queue.append(new_path)
    return None

solution = water_jug_bfs()
print("BFS Solution path:")
for step in solution:
    print(step)

def water_jug_dfs():
    start = (0, 0)
    stack = [[start]]
    visited = set()

    while stack:
        path = stack.pop()
        state = path[-1]

        if state[0] == GOAL or state[1] == GOAL:
            return path

        if state in visited:
            continue
        visited.add(state)

        x, y = state

        next_states = [
            (JUG1, y),
            (x, JUG2),
            (0, y),
            (x, 0),
            (x - min(x, JUG2 - y), y + min(x, JUG2 - y)),
            (x + min(y, JUG1 - x), y - min(y, JUG1 - x))
        ]

        for nxt in next_states:
            if nxt not in visited:
                new_path = list(path)
                new_path.append(nxt)
                stack.append(new_path)
    return None

solution = water_jug_dfs()
print("DFS Solution path:")
for step in solution:
    print(step)

import heapq

def heuristic(state):
    x, y = state
    return min(abs(x - GOAL), abs(y - GOAL))

def a_star_water_jug():
    start = (0, 0)
    open_list = []
    heapq.heappush(open_list, (heuristic(start), 0, [start]))
    visited = {}

    while open_list:
        f, g, path = heapq.heappop(open_list)
        state = path[-1]

        if state[0] == GOAL or state[1] == GOAL:
            return path

        if state in visited and visited[state] <= g:
            continue
        visited[state] = g

        x, y = state
        next_states = [
            (JUG1, y),
            (x, JUG2),
            (0, y),
            (x, 0),
            (x - min(x, JUG2 - y), y + min(x, JUG2 - y)),
            (x + min(y, JUG1 - x), y - min(y, JUG1 - x))
        ]

        for nxt in next_states:
            if nxt not in visited or g + 1 < visited.get(nxt, float('inf')):
                new_path = list(path)
                new_path.append(nxt)
                new_g = g + 1
                new_f = new_g + heuristic(nxt)
                heapq.heappush(open_list, (new_f, new_g, new_path))

solution = a_star_water_jug()
print("A* Solution path:")
for step in solution:
    print(step)

"""
### Reflection Questions:
1. Compare the solution paths found by BFS, DFS, and A*.
ANSWER:

BFS Solution path:
(0, 0)
(4, 0)
(1, 3)
DFS Solution path:
(0, 0)
(0, 3)
(3, 0)
(3, 3)
(4, 2)
(4, 0)
(1, 3)
A* Solution path:
(0, 0)
(4, 0)
(1, 3)

2. Which algorithm gives the shortest path? Why?
Answer:

BFS aur A*:
(0, 0) → (4, 0) → (1, 3)

3. Which algorithm is more efficient in terms of time and memory?
ANSWER:

DFS:
Memory efficient hai, kyunki stack use karta hai aur sirf ek path store karta hai.
Lekin time efficient nahi hai, kyunki useless states explore kar sakta hai.

BFS:
Time efficient hai (shortest path guarantee deta hai).
Lekin memory heavy hai, kyunki queue mein saare paths ek saath store karta hai.

A*:
Time aur memory dono mein balanced hota hai.
BFS ki tarah shortest path deta hai, aur DFS se kam extra states explore karta hai (thanks to heuristic).
"""